apiVersion: v1
kind: Service
metadata:
  name: datavault-app-service
  namespace: datavault
spec:
  selector:
    app: datavault-app
  ports:
  - port: 80
    targetPort: 3000
    nodePort: 30003
  type: NodePort
