apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: datavault-db
  namespace: datavault
spec:
  serviceName: "db-service"
  replicas: 1
  selector:
    matchLabels:
      app: datavault-db
  template:
    metadata:
      labels:
        app: datavault-db
    spec:
      containers:
      - name: datavault-db
        image: mariadb:11
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: MYSQL_ROOT_PASSWORD

        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: DB_NAME
      
        volumeMounts:
        - name: db-storage
          mountPath: /var/lib/mysql

  volumeClaimTemplates:
  - metadata:
      name: db-storage
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 500Mi
